development:
  adapter: mysql2
  encoding: utf8
  database: listing
  username: root
  password: r00t
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: listingtest
  username: root
  password: r00t
  host: 127.0.0.1
  port: 3306
  
production:
  adapter: mysql2
  encoding: utf8
  database: listing
  username: root
  password: r00t
  host: 127.0.0.1
  port: 3306